//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeListing.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JobEntities : DbContext
    {
        public JobEntities()
            : base("name=JobEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DEPARTMENT> DEPARTMENTs { get; set; }
        public virtual DbSet<JOB> JOBS { get; set; }
        public virtual DbSet<LOCATION> LOCATIONs { get; set; }

        public System.Data.Entity.DbSet<EmployeeListing.Models.ViewModels.JobViewModel> JobViewModels { get; set; }

        public System.Data.Entity.DbSet<EmployeeListing.Models.ViewModels.LocationViewModel> LocationViewModels { get; set; }

        public System.Data.Entity.DbSet<EmployeeListing.Models.ViewModels.DepartmentViewModel> DepartmentViewModels { get; set; }
    }
}
